Add MAE / TMAE adaptation experiments (#139)
* Add launch script

* Remove checkpointing

* Update scripts

* Switch hyperparameters

* Fix config

* Add references

* Add script to verify manifest files

* minor

* Update references

* Add launch script

* Update starting point

* Update configs

* Fix config

* Add checkpointing

* Update references

* Add launch script

* Update script

* Add launch script

* Update trifinger

* Add ViT-L

* Add conda env

* Add launch scripts

* Make executable

* Update timeout_hour

* Remove conda

* Add script

* Add gradient clipping

* input_size --> img_size

* Fix bug

* Minimum version of hydra-core on adaptation-v3 (#145)

I ran into issues trying to install because my hydra-core version was too low 
```
ImportError: cannot import name 'compose' from 'hydra'
```
Setting the version to 1.2.0 resolved the issue

* Add TMAE CLS token logic (#146)

* Add TMAE CLS token logic

* Minor

* revert

* rename

* Add v1 configs

* Add launch script

* Add timeout

* Update debug script

* Add script

* Add gibson runs

* Add objectnav launch script

* Add launch script

* Add launch script

* switch yixinlin maksymets

* Fix script

* Fix partition

* Add launch script

* Update script

* Fix script

* Update script

* Fix max_norm

* Fix code style issues with Black

---------

Co-authored-by: Vincent-Pierre BERGES <28320361+vincentpierre@users.noreply.github.com>
Co-authored-by: bot <bot@fb.com>